fix example: switch upper and lower bound in update
Simple-Robotics/proxsuite pull request #139
Opened 2022-12-13 09:04 UTC by fabinsch

We had timeouts in debug mode on windows because the bounds were updated in the wrong order and it took too long to reach the maximum number of iterations.

2022-12-13 09:38 UTC, jcarpent approved these changes
Super nice fix. Thanks a lot @fabinsch

2022-12-14 10:08 UTC, fabinsch commented on examples/cpp/solve_without_api.cpp
> +  ::proxsuite::proxqp::utils::rand::set_seed(1);
not really. I just wanted to have the same behavior for windows as for mac and linux.

Currently, not setting the seed at all leads to always the same seed in mac and linux, but to a random seed in windows. So this example is always the same for mac and linux, but it is always different on windows. 

I added this line here to have always the same example everywhere. But maybe I should rather work on the windows random number generator that by default it always has the same seed ? What do you think ?

2022-12-14 10:12 UTC, jcarpent commented on examples/cpp/solve_without_api.cpp
> +  ::proxsuite::proxqp::utils::rand::set_seed(1);
as it is an example, it should be minimalist. So, if the feature is not important, we should remove it.

2022-12-14 10:25 UTC, fabinsch commented on examples/cpp/solve_without_api.cpp
> +  ::proxsuite::proxqp::utils::rand::set_seed(1);
ok, I removed it here. And in general, I am setting a seed for windows (as it is done for macOS and linux currently).

2022-12-14 17:18 UTC, jcarpent commented on include/proxsuite/linalg/veg/internal/macros.hpp
> +#define CHECK_DATA(size, expected_size)                                        \
Should be renamed in PROXSUITE_CHECK_SIZE

2022-12-14 17:24 UTC, jcarpent requested changes

2022-12-14 17:24 UTC, jcarpent commented on include/proxsuite/linalg/veg/internal/macros.hpp
> +#define CHECK_DATA(size, expected_size)                                        \
It would be nice to just use it locally as I don't think it is useful elsewhere

2022-12-14 17:30 UTC, jcarpent approved these changes

2022-12-14 18:49 UTC, merged